const poemsArray = [
    "Roses are red,\nPizzas are too,\nI ordered a large,\nAnd none of it's for you.",
    "Love is like a pizza,\nWarm, delightful and cheesy,\nBut it's best enjoyed,\nWith someone not too greasy.",
    "Amidst the glow of screens,\nPizza warms my solitary heart,\nBytes and bites, my dual arts.",
    "Lost in the digital sea,\nI find solace in a slice,\nMelted cheese, life's spice.",
    "To the lighthouse of my WiFi,\nGuide my pizza's delivery swift,\nFor love and hunger, I drift.",
    "Chatrooms buzzing, keyboards click,\nYet in the quiet of the night,\nPizza's aroma feels just right.",
    "Love letters in binary,\nYet, the heart craves something primary,\nCheese and crust, a love so culinary.",
    "Pixels portray our modern love,\nBut pizza? Timeless, from above,\nBaked warmth, a digital world devoid of.",
    "Love's vast ocean, the internet deep,\nYet in my kitchen, passions leap,\nA pizza, my heart to keep.",
    "Tweets flutter, posts rise and fall,\nIn pizza's embrace, I recall,\nTrue love's timeless protocol.",
    "Love's algorithm, complex and vast,\nYet, pizza's allure, unsurpassed,\nIn melted moments, memories cast.",
    "Within the screen's cold light,\nPizza brings a warmth so bright,\nLove tangible, every bite.",
    "Love online, fleeting and fast,\nPizza's comfort, ever to last,\nIn its crust, memories of the past.",
    "Data flows, love's new stream,\nYet pizza remains, a tangible dream,\nWarm and real, love's supreme.",
    "The web weaves tales of modern age,\nYet pizza, timeless, turns the page,\nLove's true story, stage by stage.",
    "Emojis convey, feelings slight,\nBut pizza, in its savory might,\nWhispers of love, every bite.",
    "In the vast digital sprawl,\nPizza stands, love's beckoning call,\nReal, warm, breaking the protocol.",
    "Online, love's echo may fleet,\nBut in pizza's rhythm, hearts beat,\nLove's true form, savory and sweet.",
    "In the vast digital sprawl,\nPizza stands, love's beckoning call,\nReal, warm, breaking the protocol.",
    "Pixels portray our modern love,\nBut pizza, in its golden glow,\nWhispers of love, stories to bestow.",
    "Amidst the digital, love's cart,\nPizza offers a restart,\nLove's true form, ever smart.",
    "In the vastness of the online tide,\nPizza stands, by love's side,\nWarm and real, love's true guide.",
    "Streams of data, love's new age plea,\nYet pizza, in its simplicity,\nTells of love, pure and free.",
    "Amidst the hum of servers, so fleet,\nPizza offers a retreat,\nWhere digital and real love meet.",
    "To the web, hearts may race,\nBut pizza offers an embrace,\nLove's true form, in every trace.",
    "In the web's vast domain so wide,\nPizza stands, love's true guide,\nIn its warmth, emotions reside.",
    "Love online, a modern spree,\nYet pizza, with its legacy,\nTells of love, wild and free.",
    "Amidst the glow of LED light,\nPizza offers love, pure and bright,\nAn embrace, holding tight.",
    "Algorithms define love's new start,\nYet pizza remains, love's true part,\nAn ode to the culinary art.",
    "Amidst the digital, love's art,\nPizza, timeless, plays its part,\nWhispers of love, straight from the heart.",
    "In the online maze, hearts dart,\nYet, pizza's allure, off the chart,\nIts warmth, love's counterpart.",
    "Amidst pixels and data so smart,\nPizza remains, love's true heart,\nA symphony, every part.",
    "To the lighthouse of my web's glow,\nPizza's warmth begins to grow,\nA love story, bite by bite, it does show.",
    "In the digital night's afterglow,\nPizza stands, love's true bow,\nA timeless story, its warmth does bestow.",
    "Amidst the bytes, love might slow,\nBut pizza, in its radiant throw,\nWhispers tales of love, in each tow.",
    "Love's new age, fast and low,\nYet, pizza stands, casting a golden glow,\nStories of love, it does bestow.",
    "In the online realm, love might forgo,\nBut pizza, with its dough,\nRekindles love, making it grow.",
    //... add more poems here
];
