const poemsArray = [
    "Roses are red,\nPizzas are too,\nI ordered a large,\nAnd none of it's for you.",
    "Love is like a pizza,\nWarm,\ndelightful and cheesy,\nBut it's best enjoyed,\nWith someone not too greasy.",
    "Amidst the glow of screens,\nPizza warms my solitary heart,\nBytes and bites,\nmy dual arts.",
    "Lost in the digital sea,\nI find solace in a slice,\nMelted cheese,\nlife's spice.",
    "To the lighthouse of my WiFi,\nGuide my pizza's delivery swift,\nFor love and hunger,\nI drift.",
    "Chatrooms buzzing,\nkeyboards click,\nYet in the quiet of the night,\nPizza's aroma feels just right.",
    "Love letters in binary,\nYet,\nthe heart craves something primary,\nCheese and crust,\na love so culinary.",
    "Pixels portray our modern love,\nBut pizza? Timeless,\nfrom above,\nBaked warmth,\na digital world devoid of.",
    "Love's vast ocean,\nthe internet deep,\nYet in my kitchen,\npassions leap,\nA pizza,\nmy heart to keep.",
    "Tweets flutter,\nposts rise and fall,\nIn pizza's embrace,\nI recall,\nTrue love's timeless protocol.",
    "Love's algorithm,\ncomplex and vast,\nYet,\npizza's allure,\nunsurpassed,\nIn melted moments,\nmemories cast.",
    "Within the screen's cold light,\nPizza brings a warmth so bright,\nLove tangible,\nevery bite.",
    "Love online,\nfleeting and fast,\nPizza's comfort,\never to last,\nIn its crust,\nmemories of the past.",
    "Data flows,\nlove's new stream,\nYet pizza remains,\na tangible dream,\nWarm and real,\nlove's supreme.",
    "The web weaves tales of modern age,\nYet pizza,\ntimeless,\nturns the page,\nLove's true story,\nstage by stage.",
    "Emojis convey,\nfeelings slight,\nBut pizza,\nin its savory might,\nWhispers of love,\nevery bite.",
    "In the vast digital sprawl,\nPizza stands,\nlove's beckoning call,\nReal,\nwarm,\nbreaking the protocol.",
    "Online,\nlove's echo may fleet,\nBut in pizza's rhythm,\nhearts beat,\nLove's true form,\nsavory and sweet.",
    "In the vast digital sprawl,\nPizza stands,\nlove's beckoning call,\nReal,\nwarm,\nbreaking the protocol.",
    "Pixels portray our modern love,\nBut pizza,\nin its golden glow,\nWhispers of love,\nstories to bestow.",
    "Amidst the digital,\nlove's cart,\nPizza offers a restart,\nLove's true form,\never smart.",
    "In the vastness of the online tide,\nPizza stands,\nby love's side,\nWarm and real,\nlove's true guide.",
    "Streams of data,\nlove's new age plea,\nYet pizza,\nin its simplicity,\nTells of love,\npure and free.",
    "Amidst the hum of servers,\nso fleet,\nPizza offers a retreat,\nWhere digital and real love meet.",
    "To the web,\nhearts may race,\nBut pizza offers an embrace,\nLove's true form,\nin every trace.",
    "In the web's vast domain so wide,\nPizza stands,\nlove's true guide,\nIn its warmth,\nemotions reside.",
    "Love online,\na modern spree,\nYet pizza,\nwith its legacy,\nTells of love,\nwild and free.",
    "Amidst the glow of LED light,\nPizza offers love,\npure and bright,\nAn embrace,\nholding tight.",
    "Algorithms define love's new start,\nYet pizza remains,\nlove's true part,\nAn ode to the culinary art.",
    "Amidst the digital,\nlove's art,\nPizza,\ntimeless,\nplays its part,\nWhispers of love,\nstraight from the heart.",
    "In the online maze,\nhearts dart,\nYet,\npizza's allure,\noff the chart,\nIts warmth,\nlove's counterpart.",
    "Amidst pixels and data so smart,\nPizza remains,\nlove's true heart,\nA symphony,\nevery part.",
    "To the lighthouse of my web's glow,\nPizza's warmth begins to grow,\nA love story,\nbite by bite,\nit does show.",
    "In the digital night's afterglow,\nPizza stands,\nlove's true bow,\nA timeless story,\nits warmth does bestow.",
    "Amidst the bytes,\nlove might slow,\nBut pizza,\nin its radiant throw,\nWhispers tales of love,\nin each tow.",
    "Love's new age,\nfast and low,\nYet,\npizza stands,\ncasting a golden glow,\nStories of love,\nit does bestow.",
    "In the online realm,\nlove might forgo,\nBut pizza,\nwith its dough,\nRekindles love,\nmaking it grow.",
    "In a vast universe so wide,\nPizza becomes our singular guide,\nIs love real\nor just pride?\nOr merely flavors that coincide?",
    "Existence is fleeting and brief,\nYet\npizza offers some relief,\nLove's joy or its grief,\nIn every slice\na belief.",
    "Why are we here\nand to what end?\nFor love\nor just to attend,\nA pizza party with a friend,\nSeeking answers around the bend.",
    "The void stares back\nso vast,\nYet\npizza's warmth contrasts,\nThe questions of the past,\nLove's moment\nwill it last?",
    "In a world\nso uncertain and hazy,\nLove's like a pizza\nwarm and cheesy,\nBut is it real\nor just a phase we,\nNavigate\nlost and uneasy?",
    "To be or not\nthe eternal query,\nYet\npizza's allure is not so eerie,\nDoes love's truth make us teary,\nOr is it just culinary theory?",
    "In the cosmos\nwhere do we stand?\nWith a pizza slice in hand,\nIs love scripted\nor just unplanned?\nLife's mysteries\nlike grains of sand.",
    "Existential dread\nthe human plight,\nYet pizza brings a spark so bright,\nIs love the answer\nor just a slight,\nGlimmer in the endless night?",
    "Life's meaning\never so elusive,\nYet pizza's charm is not reclusive,\nIs love's dance so exclusive,\nOr just flavors\neffusive and effulgent?",
    "In the abyss\nwe search for a sign,\nWith pizza and love\nthings align,\nBut what's the design,\nOf this existential line?",
    "The cosmos vast\nour place so tiny,\nYet in pizza\nwe find love's shinny,\nEcho\na tune so whiny,\nOr truth's eternal spinny?",
    "To exist or fade\nthe poignant song,\nYet with pizza\ncan we go wrong?\nDoes love to us belong,\nOr is it just a life-long gong?",
    "Sartre said\n\"Hell is other people\",\nBut with pizza\nall feels equal,\nIs love the towering steeple,\nOr just life's next sequel?",
    "Kierkegaard's leap of faith so grand,\nMeets pizza\nin love's warm land,\nIs it fate's hand,\nOr just existential sand?",
    "Camus found life absurd and stark,\nYet pizza lights the existential dark,\nIs love the needed spark,\nOr just a fleeting lark?",
    "Nietzsche proclaimed God's demise,\nBut in pizza\nlove's truth lies,\nIs it the universe's ties,\nOr just existential cries?",
    "In a society of pure desire,\nPizza\na symbol of capitalist mire,\nYet in its layers\nlove does conspire,\nA truth more profound than mere culinary fire.",
    "Does not love\nlike a pizza slice,\nOffer a temporary capitalist paradise?\nThe toppings\nchoices\nall a guise,\nFor the void it can never suffice.",
    "Love's dialectic\nmuch like cheese,\nStretches\npulls\naims to please,\nBut beneath\nthere's always unease,\nAn emptiness no pizza can appease.",
    "In the realm of the Real\nlove's a maze,\nMuch like choosing pizza's toppings and glaze,\nYet both are traps\nin capitalism's haze,\nSymbols of a society in malaise.",
    "Isn't pizza\nin its circular form,\nA representation of societal norm?\nYet love\never rebellious\never warm,\nSeeks to go beyond\nto transform.",
    "Lacan said\n'Desire is the desire of the Other',\nPizza\nthen\nthe desire of the mother?\nLove\nan attempt to seek another,\nYet both are fraught\nlike no other.",
    "In the gaze of the Other\nwe seek validation,\nIn pizza\nwe seek mere satiation,\nBut love\nit demands a foundation,\nBeyond mere capitalist jubilation.",
    "Does not the crust signify the boundary,\nOf love's limit\nits profound quandary?\nYet\nwith each bite\nthere's a sundry,\nTaste of truth\nand also\nof quandary.",
    "Hegel's dialectic\nthesis and antithesis,\nLove and pizza\na modern synthesis?\nYet\nin the jouissance\nthere's a twist,\nAn emptiness\nthat always persists.",
    "The crust\nthe boundary of the Real,\nThe toppings\nsymbols of the societal deal,\nBut love\ndoes it not make us feel,\nA rupture\na truth\nthat's truly surreal?",
    "In the Spectacle\nlove is commodified,\nLike pizza\npackaged\nand sold worldwide,\nYet\ntrue love can't be identified,\nBy capitalist measures\nhowever tried.",
    "Pizza\na comfort in late capitalism's despair,\nLove\na hope\nthin as air,\nBoth are consumed\nwith little care,\nIn the grand theatre\nof society's fair.",
    "Is not the pizza slice\nin its triangular shape,\nAn echo of the Other's gaping gape?\nLove too\ntries to drape,\nBut in the Real\nalways ends up an escape.",
    "The pepperoni\na signifier\nstands apart,\nMuch like love's ever-beating heart,\nYet both\nin the end\nare a la carte,\nTransient moments\nthat soon depart.",
    "Cheese\nstretching between slices,\nLike love's many vices,\nYet\nin the capitalist crisis,\nBoth are mere market devices.",
    "The void\never present\nalways lurking,\nIn love's shadows\nalways working,\nYet pizza\ncapitalism's perking,\nOffers a momentary shirking.",
    "Does not the oven's heat,\nSymbolize love's ultimate feat?\nYet\nin the end\nboth are bittersweet,\nMoments of joy\nand also\nof defeat.",
    "Pizza\na commodity\nin endless supply,\nLove\nthough\ncan't be bought\nno matter how high,\nYet both\nunder capitalism's sky,\nAre fleeting moments\npassing by.",
    "The sauce\nhidden\nyet profound,\nLike love's emotions\ndeep and unbound,\nYet\nin the Spectacle\nboth are drowned,\nIn the noise\nthe unending sound.",
    "Capitalism's logic\nalways consumes,\nTurning love into mere perfumes,\nYet pizza\nin its many plumes,\nOffers a joy\nthat sometimes resumes.",
    "The slice\na fragment of the whole,\nMuch like love\na part of the soul,\nYet\nin the capitalist dole,\nBoth are played\na mere role.",
    "Pizza's allure\nglobal and wide,\nMuch like love\ncan't be denied,\nYet\nbeneath the cheese\ndoes hide,\nThe truth of the system\nworldwide.",
    //... add more poems here
];
